#!/bin/sh -e

# postinst of the dbg binary package

package=liblockdev1-dbg

lib_dbg=/usr/lib/debug
file=README.debug
doc_dir=/usr/share/doc

# This installs the readme into the global directory if it isn't already there
if	[ ! -r ${lib_dbg}/${file} ]
then	if	[ -r ${doc_dir}/${package}/${file} ]
	then	cp -a ${doc_dir}/${package}/${file} ${lib_dbg}
	elif	[ -r ${doc_dir}/${package}/${file}.gz ]
	then	zcat ${doc_dir}/${package}/${file}.gz >${lib_dbg}/${file}
	fi
fi
  # end
