#!/bin/sh -e

# prerm

package=liblockdev1-dbg
libname=liblockdev.so

lib_dbg=/usr/lib/debug
file=README.debug

if	[ -d "${lib_dbg}" ]
then	ls -A1 ${lib_dbg} 2>/dev/null \
	| grep -v -e "${file}" -e ${libname} >/dev/null \
	|| if	[ -r "${lib_dbg}/${file}" ]; \
	then	rm -f ${lib_dbg}/${file} || true; \
	fi
fi
  # end
